apiVersion: v1
kind: Pod
metadata:
  name: counter-en
  namespace: efk-logging
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: Hello, are you collecting my data? $(date)"; i=$((i+1)); sleep 5; done']